replicaCount: 1
name: pm
namespace:
image:
  repository: apiserver
  tag: "0.0.1"
  pullPolicy: Never
service:
  name: nginx
  externalPort: 80
  internalPort: 5000
ingress:
  enabled: true
  host: local.ecosia.org
  annotations:
    kubernetes.io/ingress.class: nginx
flask:
  debug: false