apiVersion: v1
kind: Service
metadata:
  name: {{ template "apiserver.fullname" . }}
  labels: {{- include "apiserver.standardLabels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.internalPort }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "apiserver.matchLabels" . | nindent 6 }}
